# Generated by Django 5.1.7 on 2025-03-11 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institute', models.CharField(blank=True, default='SSVPS', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Users Table',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('designation', models.CharField(choices=[('Staff', 'Staff'), ('Professor', 'Professor'), ('Ast.Professor', 'Ast.Professor')], max_length=100)),
                ('department', models.CharField(choices=[('Admin', 'Admin'), ('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Enginnering', 'Enginnering')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profiles Table',
            },
        ),
    ]
