# Generated by Django 5.1.4 on 2025-03-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_exam_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
    ]
